package it.unina.prenotazioni.boundary.Swing;

import it.unina.prenotazioni.dto.SalaMonitoraggioDTO;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.Locale;

public class CardSala {

    private static final Color VERDE_BADGE = new Color(72, 187, 120);
    private static final Color GIALLO_BADGE = new Color(236, 201, 75);
    private static final Color ROSSO_BADGE = new Color(245, 101, 101);
    private static final Color ROSSO_AZIONE = new Color(229, 62, 62);

    // Campi legati al .form
    private JPanel cardPane;
    private JLabel lblNome;
    private JPanel pannelloBadge;
    private JLabel lblBadgeLiberi;
    private JLabel lblBadgeAttivi;
    private JLabel lblBadgeConfermati;
    private JPanel pannelloAree;
    private JButton btnElimina;
    private JLabel lblRimossa;

    public CardSala(SalaMonitoraggioDTO sala) {
        boolean attiva = sala.isAttiva();

        // Styling non configurabile nel form designer
        cardPane.setBorder(attiva
                ? new LineBorder(StileWizard.GRIGIO_BORDO, 1, true)
                : BorderFactory.createDashedBorder(new Color(204, 204, 204)));
        btnElimina.setForeground(ROSSO_AZIONE);
        btnElimina.setBackground(Color.WHITE);
        btnElimina.setFocusPainted(false);
        btnElimina.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnElimina.setBorder(BorderFactory.createCompoundBorder(
                new LineBorder(ROSSO_AZIONE, 1, true),
                new EmptyBorder(6, 14, 6, 14)));

        lblNome.setText(attiva
                ? "<html><b>" + sala.getNomeSala() + "</b></html>"
                : "<html><b><font color='#999999'>" + sala.getNomeSala()
                  + "</font></b> <font color='#E53E3E' size='2'><b>(Eliminata)</b></font></html>");

        // badge grigi se la sala è stata eliminata
        stilizzaBadge(lblBadgeLiberi, sala.getPostiLiberi(), attiva ? VERDE_BADGE : Color.GRAY, "Posti liberi");
        stilizzaBadge(lblBadgeAttivi, sala.getPostiAttivi(), attiva ? GIALLO_BADGE : Color.GRAY, "Attive (non confermate)");
        stilizzaBadge(lblBadgeConfermati, sala.getPostiConfermati(), attiva ? ROSSO_BADGE : Color.GRAY, "Confermate (presenti)");

        pannelloAree.setLayout(new FlowLayout(FlowLayout.CENTER, 6, 2));
        if (sala.getAree().isEmpty()) {
            pannelloAree.add(StileWizard.creaPill("nessuna area"));
        } else {
            for (String area : sala.getAree()) {
                pannelloAree.add(StileWizard.creaPill(area));
            }
        }

        btnElimina.setVisible(attiva);
        lblRimossa.setVisible(!attiva);
    }

    private void stilizzaBadge(JLabel badge, int valore, Color sfondo, String descrizione) {
        badge.setText(String.valueOf(valore));
        badge.setOpaque(true);
        badge.setBackground(sfondo);
        badge.setBorder(new EmptyBorder(4, 12, 4, 12));
        badge.setToolTipText(descrizione);
    }

    public JPanel getRoot() {
        return cardPane;
    }

    public void addEliminaListener(ActionListener listener) {
        btnElimina.addActionListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        cardPane = new JPanel();
        cardPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(14, 14, 14, 14), -1, 8));
        cardPane.setBackground(new Color(-1));
        lblNome = new JLabel();
        Font lblNomeFont = this.$$$getFont$$$("SansSerif", -1, 15, lblNome.getFont());
        if (lblNomeFont != null) lblNome.setFont(lblNomeFont);
        lblNome.setHorizontalAlignment(0);
        lblNome.setText("Nome sala");
        cardPane.add(lblNome, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pannelloBadge = new JPanel();
        pannelloBadge.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 5, new Insets(0, 0, 0, 0), 6, -1));
        pannelloBadge.setBackground(new Color(-1));
        pannelloBadge.setOpaque(true);
        cardPane.add(pannelloBadge, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        pannelloBadge.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        lblBadgeLiberi = new JLabel();
        Font lblBadgeLiberiFont = this.$$$getFont$$$("SansSerif", Font.BOLD, 13, lblBadgeLiberi.getFont());
        if (lblBadgeLiberiFont != null) lblBadgeLiberi.setFont(lblBadgeLiberiFont);
        lblBadgeLiberi.setForeground(new Color(-1));
        lblBadgeLiberi.setText("0");
        pannelloBadge.add(lblBadgeLiberi, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblBadgeAttivi = new JLabel();
        Font lblBadgeAttiviFont = this.$$$getFont$$$("SansSerif", Font.BOLD, 13, lblBadgeAttivi.getFont());
        if (lblBadgeAttiviFont != null) lblBadgeAttivi.setFont(lblBadgeAttiviFont);
        lblBadgeAttivi.setForeground(new Color(-1));
        lblBadgeAttivi.setText("0");
        pannelloBadge.add(lblBadgeAttivi, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblBadgeConfermati = new JLabel();
        Font lblBadgeConfermatiFont = this.$$$getFont$$$("SansSerif", Font.BOLD, 13, lblBadgeConfermati.getFont());
        if (lblBadgeConfermatiFont != null) lblBadgeConfermati.setFont(lblBadgeConfermatiFont);
        lblBadgeConfermati.setForeground(new Color(-1));
        lblBadgeConfermati.setText("0");
        pannelloBadge.add(lblBadgeConfermati, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        pannelloBadge.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(0, 4, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        pannelloAree = new JPanel();
        pannelloAree.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pannelloAree.setBackground(new Color(-1));
        pannelloAree.setOpaque(true);
        cardPane.add(pannelloAree, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnElimina = new JButton();
        btnElimina.setText("Elimina sala");
        cardPane.add(btnElimina, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblRimossa = new JLabel();
        Font lblRimossaFont = this.$$$getFont$$$("SansSerif", Font.ITALIC, 12, lblRimossa.getFont());
        if (lblRimossaFont != null) lblRimossa.setFont(lblRimossaFont);
        lblRimossa.setForeground(new Color(-8882046));
        lblRimossa.setHorizontalAlignment(0);
        lblRimossa.setText("Rimossa dall'elenco pubblico");
        cardPane.add(lblRimossa, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return cardPane;
    }
}
