package it.unina.prenotazioni.boundary.Swing;

import it.unina.prenotazioni.dto.PrenotazioneDTO;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionListener;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

public class CardPrenotazione {

    private static final DateTimeFormatter FORMATO_DATA = DateTimeFormatter.ofPattern("dd-MM-yyyy");
    private static final Color ROSSO_AZIONE = new Color(229, 62, 62);

    // Campi legati al .form
    private JPanel cardPane;
    private JPanel intestazione;
    private JLabel lblId;
    private JLabel lblStato;
    private JLabel lblData;
    private JLabel lblOrario;
    private JLabel lblPosizione;
    private JPanel pannelloAzioni;
    private JButton btnCheckIn;
    private JButton btnAnnulla;

    public CardPrenotazione(PrenotazioneDTO prenotazione) {
        // Styling non configurabile nel form designer
        cardPane.setBorder(new LineBorder(StileWizard.GRIGIO_BORDO, 1, true));
        StileWizard.stilizzaBottone(btnCheckIn, StileWizard.VERDE);
        btnCheckIn.setBorder(new EmptyBorder(6, 12, 6, 12));
        btnAnnulla.setForeground(ROSSO_AZIONE);
        btnAnnulla.setBackground(Color.WHITE);
        btnAnnulla.setFocusPainted(false);
        btnAnnulla.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnAnnulla.setBorder(BorderFactory.createCompoundBorder(
                new LineBorder(ROSSO_AZIONE, 1, true),
                new EmptyBorder(5, 12, 5, 12)));

        lblId.setText("Prenotazione #" + prenotazione.getIdPrenotazione());
        String dataFormattata = prenotazione.getData() == null ? "" : prenotazione.getData().format(FORMATO_DATA);
        lblData.setText("Data: " + dataFormattata);
        lblOrario.setText("Orario: " + prenotazione.getFasciaOraria());
        lblPosizione.setText(prenotazione.getNomeSala() + " - " + prenotazione.getTipologiaArea()
                + " - Postazione #" + prenotazione.getNumeroPostazione());
        stilizzaBadge(prenotazione.getStato());

        // azioni disponibili solo sulle prenotazioni ATTIVE
        pannelloAzioni.setVisible("ATTIVA".equals(prenotazione.getStato()));
    }

    private void stilizzaBadge(String stato) {
        Color sfondo;
        Color testo;
        switch (stato == null ? "" : stato) {
            case "ATTIVA" -> {
                sfondo = new Color(235, 244, 255);
                testo = new Color(49, 130, 206);
            }
            case "CONFERMATA" -> {
                sfondo = new Color(198, 246, 213);
                testo = new Color(56, 161, 105);
            }
            case "ANNULLATA" -> {
                sfondo = new Color(254, 215, 215);
                testo = new Color(229, 62, 62);
            }
            default -> {
                sfondo = new Color(226, 232, 240);
                testo = new Color(74, 85, 104);
            }
        }
        lblStato.setText(stato);
        lblStato.setOpaque(true);
        lblStato.setBackground(sfondo);
        lblStato.setForeground(testo);
        lblStato.setBorder(new EmptyBorder(3, 10, 3, 10));
    }

    public JPanel getRoot() {
        return cardPane;
    }

    public void addCheckInListener(ActionListener listener) {
        btnCheckIn.addActionListener(listener);
    }

    public void addAnnullaListener(ActionListener listener) {
        btnAnnulla.addActionListener(listener);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        cardPane = new JPanel();
        cardPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(12, 14, 12, 14), -1, 6));
        cardPane.setBackground(new Color(-1));
        intestazione = new JPanel();
        intestazione.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        intestazione.setBackground(new Color(-1));
        intestazione.setOpaque(true);
        cardPane.add(intestazione, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblId = new JLabel();
        Font lblIdFont = this.$$$getFont$$$("SansSerif", Font.BOLD, 14, lblId.getFont());
        if (lblIdFont != null) lblId.setFont(lblIdFont);
        lblId.setText("Prenotazione #—");
        intestazione.add(lblId, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        intestazione.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        lblStato = new JLabel();
        Font lblStatoFont = this.$$$getFont$$$("SansSerif", Font.BOLD, 11, lblStato.getFont());
        if (lblStatoFont != null) lblStato.setFont(lblStatoFont);
        lblStato.setText("STATO");
        intestazione.add(lblStato, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblData = new JLabel();
        lblData.setForeground(new Color(-8882046));
        lblData.setText("Data: —");
        cardPane.add(lblData, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblOrario = new JLabel();
        lblOrario.setForeground(new Color(-8882046));
        lblOrario.setText("Orario: —");
        cardPane.add(lblOrario, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblPosizione = new JLabel();
        lblPosizione.setForeground(new Color(-8882046));
        lblPosizione.setText("sala - area - Postazione #—");
        cardPane.add(lblPosizione, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pannelloAzioni = new JPanel();
        pannelloAzioni.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new Insets(6, 0, 0, 0), 8, -1));
        pannelloAzioni.setBackground(new Color(-1));
        pannelloAzioni.setOpaque(true);
        cardPane.add(pannelloAzioni, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCheckIn = new JButton();
        btnCheckIn.setBackground(new Color(-12010632));
        btnCheckIn.setForeground(new Color(-1));
        btnCheckIn.setText("Effettua Check-In");
        pannelloAzioni.add(btnCheckIn, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnAnnulla = new JButton();
        btnAnnulla.setText("Annulla");
        pannelloAzioni.add(btnAnnulla, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        pannelloAzioni.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /*
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /*
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return cardPane;
    }
}
