package it.unina.prenotazioni.boundary.Swing;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import it.unina.prenotazioni.dto.PrenotazioneDTO;

import javax.swing.*;
import javax.swing.border.LineBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Locale;

public class PrenotazioneConfermata {

    // Campi legati al .form
    private JPanel confermataPane;
    private JPanel header;
    private JLabel lblTitolo;
    private JButton btnLogout;
    private JPanel pannelloSteps;
    private JLabel lblSteps;
    private JPanel pannelloContenuto;
    private JPanel cardConfermata;
    private JPanel pannelloIcona;
    private JLabel lblTitolone;
    private JLabel lblMessaggio;
    private JPanel pannelloBox;
    private JLabel lblBoxRiga1;
    private JLabel lblBoxRiga2;
    private JButton btnDashboard;

    // Stato interno
    private final StatoWizard stato;
    private JFrame frameCorrente;

    public PrenotazioneConfermata(StatoWizard stato, PrenotazioneDTO prenotazione) {
        this.stato = stato;

        // Styling non configurabile nel form designer
        StileWizard.stilizzaLogout(btnLogout);
        StileWizard.stilizzaBottone(btnDashboard, StileWizard.VIOLA);
        StileWizard.bordaCard(cardConfermata);
        lblSteps.setText(StileWizard.htmlSteps(6));
        pannelloBox.setBorder(new LineBorder(StileWizard.GRIGIO_BORDO, 1, true));

        pannelloIcona.setLayout(new GridBagLayout());
        pannelloIcona.setBackground(Color.WHITE);
        pannelloIcona.add(new CerchioSpunta());

        lblMessaggio.setText("<html><div style='text-align:center;'>La prenotazione <b>#"
                + prenotazione.getIdPrenotazione() + "</b> è stata registrata in stato <b><font color='#3182CE'>"
                + prenotazione.getStato() + "</font></b>.</div></html>");
        lblBoxRiga1.setText(prenotazione.getNomeSala() + " · " + prenotazione.getTipologiaArea()
                + " · Postazione #" + prenotazione.getNumeroPostazione());
        lblBoxRiga2.setText("<html>" + StileWizard.formattaData(prenotazione.getData())
                + " &nbsp;|&nbsp; " + prenotazione.getFasciaOraria() + "</html>");

        btnLogout.addActionListener(e -> {
            frameCorrente.dispose();
            new Login().apriLogin();
        });
        btnDashboard.addActionListener(e -> {
            frameCorrente.dispose();
            new DashboardStudente().apriDashboard(stato.getStudente());
        });
    }

    // --- APRI FORM ---

    public JFrame apriForm() {
        frameCorrente = new JFrame("Prenotazione Confermata");
        frameCorrente.setContentPane(confermataPane);
        frameCorrente.setSize(1000, 1000);
        frameCorrente.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frameCorrente.setLocationRelativeTo(null);
        frameCorrente.setResizable(false);
        frameCorrente.setVisible(true);
        return frameCorrente;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        confermataPane = new JPanel();
        confermataPane.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        confermataPane.setBackground(new Color(-5192482));
        header = new JPanel();
        header.setLayout(new GridLayoutManager(1, 3, new Insets(10, 15, 10, 15), -1, -1));
        header.setBackground(new Color(-8621082));
        header.setOpaque(true);
        confermataPane.add(header, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblTitolo = new JLabel();
        Font lblTitoloFont = this.$$$getFont$$$("SansSerif", Font.BOLD, 20, lblTitolo.getFont());
        if (lblTitoloFont != null) lblTitolo.setFont(lblTitoloFont);
        lblTitolo.setForeground(new Color(-1));
        lblTitolo.setText("  Dashboard Studente");
        header.add(lblTitolo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        header.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        btnLogout = new JButton();
        btnLogout.setText("Logout");
        header.add(btnLogout, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pannelloSteps = new JPanel();
        pannelloSteps.setLayout(new GridLayoutManager(1, 1, new Insets(12, 20, 12, 20), -1, -1));
        pannelloSteps.setBackground(new Color(-5192482));
        pannelloSteps.setOpaque(true);
        confermataPane.add(pannelloSteps, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblSteps = new JLabel();
        lblSteps.setForeground(new Color(-6710887));
        lblSteps.setHorizontalAlignment(0);
        lblSteps.setText("1 Data  Sala  ──  2 Fascia Oraria  ──  3 Area  ──  4 Postazione  ──  5 Conferma");
        lblSteps.setDisplayedMnemonic(' ');
        lblSteps.setDisplayedMnemonicIndex(7);
        pannelloSteps.add(lblSteps, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pannelloContenuto = new JPanel();
        pannelloContenuto.setLayout(new GridLayoutManager(1, 3, new Insets(15, 30, 20, 30), -1, -1));
        pannelloContenuto.setBackground(new Color(-5192482));
        pannelloContenuto.setOpaque(true);
        confermataPane.add(pannelloContenuto, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        pannelloContenuto.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        cardConfermata = new JPanel();
        cardConfermata.setLayout(new GridLayoutManager(5, 1, new Insets(20, 20, 20, 20), -1, 18));
        cardConfermata.setBackground(new Color(-1));
        cardConfermata.setOpaque(true);
        pannelloContenuto.add(cardConfermata, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(520, -1), null, 0, false));
        pannelloIcona = new JPanel();
        pannelloIcona.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pannelloIcona.setBackground(new Color(-1));
        pannelloIcona.setOpaque(true);
        cardConfermata.add(pannelloIcona, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 100), null, 0, false));
        lblTitolone = new JLabel();
        Font lblTitoloneFont = this.$$$getFont$$$("SansSerif", Font.BOLD, 26, lblTitolone.getFont());
        if (lblTitoloneFont != null) lblTitolone.setFont(lblTitoloneFont);
        lblTitolone.setHorizontalAlignment(0);
        lblTitolone.setText("Prenotazione Confermata");
        cardConfermata.add(lblTitolone, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblMessaggio = new JLabel();
        lblMessaggio.setForeground(new Color(-6710887));
        lblMessaggio.setHorizontalAlignment(0);
        lblMessaggio.setText("La prenotazione è stata registrata.");
        cardConfermata.add(lblMessaggio, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pannelloBox = new JPanel();
        pannelloBox.setLayout(new GridLayoutManager(2, 1, new Insets(14, 14, 14, 14), -1, 6));
        pannelloBox.setBackground(new Color(-460036));
        pannelloBox.setOpaque(true);
        cardConfermata.add(pannelloBox, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblBoxRiga1 = new JLabel();
        Font lblBoxRiga1Font = this.$$$getFont$$$("SansSerif", Font.BOLD, 14, lblBoxRiga1.getFont());
        if (lblBoxRiga1Font != null) lblBoxRiga1.setFont(lblBoxRiga1Font);
        lblBoxRiga1.setHorizontalAlignment(0);
        lblBoxRiga1.setText("sala · area · postazione");
        pannelloBox.add(lblBoxRiga1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblBoxRiga2 = new JLabel();
        lblBoxRiga2.setForeground(new Color(-6710887));
        lblBoxRiga2.setHorizontalAlignment(0);
        lblBoxRiga2.setText("data | fascia");
        pannelloBox.add(lblBoxRiga2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnDashboard = new JButton();
        btnDashboard.setBackground(new Color(-8621082));
        btnDashboard.setForeground(new Color(-1));
        btnDashboard.setText("Torna alla dashboard");
        cardConfermata.add(btnDashboard, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        pannelloContenuto.add(spacer3, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /*
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /*
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return confermataPane;
    }

    private static class CerchioSpunta extends JPanel {

        CerchioSpunta() {
            setPreferredSize(new Dimension(90, 90));
            setOpaque(false);
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(new Color(198, 246, 213));
            g2.fillOval(0, 0, getWidth(), getHeight());
            g2.setColor(new Color(56, 161, 105));
            g2.setStroke(new BasicStroke(6f, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND));
            int w = getWidth();
            int h = getHeight();
            g2.drawPolyline(
                    new int[]{Math.round(w * 0.30f), Math.round(w * 0.45f), Math.round(w * 0.72f)},
                    new int[]{Math.round(h * 0.52f), Math.round(h * 0.66f), Math.round(h * 0.36f)}, 3);
            g2.dispose();
        }
    }
}
